[workspace]

members = [
    "crates/nbformat",
    "crates/runtimelib",
    "crates/jupyter-serde",
    "crates/sidecar",
    "crates/jupyter-websocket-client",
]

resolver = "2"

[workspace.dependencies]
anyhow = "1.0.80"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
uuid = { version = "1.7.0", features = ["serde", "v5"] }
chrono = { version = "0.4.34", default-features = false, features = [
    "std",
    "serde",
] }
futures = "0.3"
bytes = "1.5.0"
base64 = "0.22.0"
