[package]
name = "jupyter-protocol"
version = "0.1.0"
edition = "2021"
description = "Connect to Jupyter Servers over WebSockets"
repository = "https://github.com/runtimed/runtimed"
license = "BSD-3-Clause"

[dependencies]
jupyter-serde = { path = "../jupyter-serde", version = "0.4.0" }
async-trait = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
