[package]
name = "jupyter-serde"
version = "0.2.1"
edition = "2021"
description = "Serialization and Deserialization for Jupyter related data structures"
repository = "https://github.com/runtimed/runtimed"
license = "BSD-3-Clause"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
thiserror = "1.0"
