[package]
name = "jupyter-websocket-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
serde_json = "1.0.113"
tokio = { version = "1.36.0", features = ["full"] }
reqwest = { version = "0.12.8", features = ["json"] }
url = "2.5.2"
async-tungstenite = { version = "0.22", features = ["tokio-runtime"] }
futures = "0.3"
serde = { version = "1.0.196", features = ["derive"] }
uuid = { version = "1.7.0", features = ["serde", "v5"] }

runtimelib = { path = "../runtimelib" }
