[package]
name = "jupyter-websocket-client"
version = "0.3.0"
edition = "2021"
description = "Connect to Jupyter Servers over WebSockets"
repository = "https://github.com/runtimed/runtimed"
license = "BSD-3-Clause"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
tokio = { version = "1.36.0", features = ["full"] }
reqwest = { version = "0.12.8", features = ["json"] }
jupyter-serde = { path = "../jupyter-serde", version = "0.3.0" }
url = "2.5.2"
async-tungstenite = { version = "0.22", features = ["tokio-runtime"] }
runtimelib = { path = "../runtimelib", version = "0.18.0" }
