[package]
name = "nbformat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
serde_json = "1.0.113"
serde = { version = "1.0.196", features = ["derive"] }
uuid = { version = "1.7.0", features = ["serde", "v5"] }
runtimelib = { path = "../runtimelib" }
