[package]
name = "nbformat"
version = "0.3.0"
edition = "2021"
description = "Parse Jupyter Notebooks"
repository = "https://github.com/runtimed/runtimed"
license = "BSD-3-Clause"

[dependencies]
chrono = "0.4"
anyhow = "1.0.80"
jupyter-serde = { version = "0.2.0", path = "../jupyter-serde" }
serde_json = "1.0.113"
serde = { version = "1.0.196", features = ["derive"] }
thiserror = "1.0"
uuid = { version = "1.7.0", features = ["serde", "v5"] }
