[package]
name = "nbformat"
version = "0.6.0"
edition = "2021"
description = "Parse Jupyter Notebooks"
repository = "https://github.com/runtimed/runtimed"
license = "BSD-3-Clause"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
jupyter-serde = { version = "0.5.0", path = "../jupyter-serde" }
thiserror = "1.0"
